# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcu_eta_ <- function(eta, ksi, y, z, R, ind) {
    invisible(.Call('_VEMIRT_calcu_eta_', PACKAGE = 'VEMIRT', eta, ksi, y, z, R, ind))
}

update_sigma_i <- function(omega, A, eta1_i, eta2_i) {
    .Call('_VEMIRT_update_sigma_i', PACKAGE = 'VEMIRT', omega, A, eta1_i, eta2_i)
}

update_mu_i <- function(sigma_i, eta1_i, eta2_i, A, B, R, y_i) {
    .Call('_VEMIRT_update_mu_i', PACKAGE = 'VEMIRT', sigma_i, eta1_i, eta2_i, A, B, R, y_i)
}

ve_step <- function(sigma_, mu_, sig_mu_sum, y, old_A, old_B, R, old_sig, old_eta1, old_eta2) {
    invisible(.Call('_VEMIRT_ve_step', PACKAGE = 'VEMIRT', sigma_, mu_, sig_mu_sum, y, old_A, old_B, R, old_sig, old_eta1, old_eta2))
}

calcu_sigma_cmle_cpp <- function(sigma_hat, sigma0, tol) {
    .Call('_VEMIRT_calcu_sigma_cmle_cpp', PACKAGE = 'VEMIRT', sigma_hat, sigma0, tol)
}

update_ksi_ij <- function(Aj, Bj, mu_i, sigma_mu_i, yij, Rj, ind, sq_rt = TRUE) {
    .Call('_VEMIRT_update_ksi_ij', PACKAGE = 'VEMIRT', Aj, Bj, mu_i, sigma_mu_i, yij, Rj, ind, sq_rt)
}

update_Aj_ <- function(Mj, Bj, Rj, yj, sig_mu_sum, mu_, eta1_j, eta2_j) {
    .Call('_VEMIRT_update_Aj_', PACKAGE = 'VEMIRT', Mj, Bj, Rj, yj, sig_mu_sum, mu_, eta1_j, eta2_j)
}

update_Bj_ <- function(Aj, Bj, Rj, mu_, eta1_j, eta2_j, yj) {
    .Call('_VEMIRT_update_Bj_', PACKAGE = 'VEMIRT', Aj, Bj, Rj, mu_, eta1_j, eta2_j, yj)
}

calcu_n2vlb_j <- function(Aj, Bj, mu_, sig_mu_sum, yj, Rj, ksi1_j, ksi2_j, eta1_j, eta2_j) {
    .Call('_VEMIRT_calcu_n2vlb_j', PACKAGE = 'VEMIRT', Aj, Bj, mu_, sig_mu_sum, yj, Rj, ksi1_j, ksi2_j, eta1_j, eta2_j)
}

calcu_n2vlb_0 <- function(sig, hat_sig, N) {
    .Call('_VEMIRT_calcu_n2vlb_0', PACKAGE = 'VEMIRT', sig, hat_sig, N)
}

calcu_entro_ <- function(sigma_, N, K) {
    .Call('_VEMIRT_calcu_entro_', PACKAGE = 'VEMIRT', sigma_, N, K)
}

vem_grm <- function(y, R, old_A, old_B, old_sig, old_ksi1, old_ksi2, Mod, max_iter = 1000L, tol_para = 1e-4, stop_cri = 2L, verbose = 1L) {
    .Call('_VEMIRT_vem_grm', PACKAGE = 'VEMIRT', y, R, old_A, old_B, old_sig, old_ksi1, old_ksi2, Mod, max_iter, tol_para, stop_cri, verbose)
}

b2gamma <- function(B, R) {
    .Call('_VEMIRT_b2gamma', PACKAGE = 'VEMIRT', B, R)
}

gamma2b <- function(gamma, R) {
    .Call('_VEMIRT_gamma2b', PACKAGE = 'VEMIRT', gamma, R)
}

calcu_Fjr <- function(Fjr, Theta_is, A, B, y_i) {
    invisible(.Call('_VEMIRT_calcu_Fjr', PACKAGE = 'VEMIRT', Fjr, Theta_is, A, B, y_i))
}

calcu_Fjrp <- function(Fjrp, Theta_is, A, B, y_i, R) {
    invisible(.Call('_VEMIRT_calcu_Fjrp', PACKAGE = 'VEMIRT', Fjrp, Theta_is, A, B, y_i, R))
}

calcu_tid_wis <- function(tid_wis, Theta_is, Theta_is__, mu_i, sigma_i, sig, Fjr, Fjrp) {
    invisible(.Call('_VEMIRT_calcu_tid_wis', PACKAGE = 'VEMIRT', tid_wis, Theta_is, Theta_is__, mu_i, sigma_i, sig, Fjr, Fjrp))
}

calcu_grad_sig <- function(old_sig, Theta_is, tid_wis) {
    .Call('_VEMIRT_calcu_grad_sig', PACKAGE = 'VEMIRT', old_sig, Theta_is, tid_wis)
}

calcu_grad_A <- function(M, Theta_is, tid_wis, Fjr, Fjrp) {
    .Call('_VEMIRT_calcu_grad_A', PACKAGE = 'VEMIRT', M, Theta_is, tid_wis, Fjr, Fjrp)
}

calcu_grad_gam <- function(old_gam, Theta_is, tid_wis, Fjr, Fjrp, y_i, R) {
    .Call('_VEMIRT_calcu_grad_gam', PACKAGE = 'VEMIRT', old_gam, Theta_is, tid_wis, Fjr, Fjrp, y_i, R)
}

update_param <- function(old_param, grad_param, vu_param, r_param, beta1, beta2, beta1t, beta2t, eps, eta) {
    .Call('_VEMIRT_update_param', PACKAGE = 'VEMIRT', old_param, grad_param, vu_param, r_param, beta1, beta2, beta1t, beta2t, eps, eta)
}

gen_theta_is <- function(mu, sigma, M) {
    .Call('_VEMIRT_gen_theta_is', PACKAGE = 'VEMIRT', mu, sigma, M)
}

iwgvem_grm <- function(y, R, old_A, old_B, old_sig, mu_n, sigma_n, Mod, S = 10L, M = 10L, beta1 = 0.9, beta2 = 0.999, eta_A = 0.05, eta_gam = 0.01, eta_sig = 0.005, eps = 0.001, max_iter = 100L, tol_para = 1e-4, verbose = 1L) {
    .Call('_VEMIRT_iwgvem_grm', PACKAGE = 'VEMIRT', y, R, old_A, old_B, old_sig, mu_n, sigma_n, Mod, S, M, beta1, beta2, eta_A, eta_gam, eta_sig, eps, max_iter, tol_para, verbose)
}

ecfa2 <- function(u, Sigma, domain, person, item, eta, new_a, new_b) {
    .Call('_VEMIRT_ecfa2', PACKAGE = 'VEMIRT', u, Sigma, domain, person, item, eta, new_a, new_b)
}

acfa2 <- function(u, indic, person, item, domain, eta, new_b, SIGMA, MU, new_a1) {
    .Call('_VEMIRT_acfa2', PACKAGE = 'VEMIRT', u, indic, person, item, domain, eta, new_b, SIGMA, MU, new_a1)
}

lb2pl <- function(u, xi, sig, new_a, new_b, SIGMA, MU) {
    .Call('_VEMIRT_lb2pl', PACKAGE = 'VEMIRT', u, xi, sig, new_a, new_b, SIGMA, MU)
}

ea2 <- function(domain, person, item, eta, SIGMA, MU, indic) {
    .Call('_VEMIRT_ea2', PACKAGE = 'VEMIRT', domain, person, item, eta, SIGMA, MU, indic)
}

ecfa3pl <- function(u, Sigma, domain, id_1, item, eta, new_s, new_a, new_b, SIGMA1, MU1, xi1) {
    .Call('_VEMIRT_ecfa3pl', PACKAGE = 'VEMIRT', u, Sigma, domain, id_1, item, eta, new_s, new_a, new_b, SIGMA1, MU1, xi1)
}

s3pl <- function(item, id_1, s, eta, new_a, s_num, new_b, u, SIGMA, MU, xi) {
    .Call('_VEMIRT_s3pl', PACKAGE = 'VEMIRT', item, id_1, s, eta, new_a, s_num, new_b, u, SIGMA, MU, xi)
}

eta3pl <- function(item, id_1, ea, xi) {
    .Call('_VEMIRT_eta3pl', PACKAGE = 'VEMIRT', item, id_1, ea, xi)
}

b3pl <- function(item, id_1, new_s, eta, u, new_a, dec_st, MU, prev_b_num, prev_b_denom, mu_b, sigma2_b) {
    .Call('_VEMIRT_b3pl', PACKAGE = 'VEMIRT', item, id_1, new_s, eta, u, new_a, dec_st, MU, prev_b_num, prev_b_denom, mu_b, sigma2_b)
}

acfa3 <- function(u, indic, id_1, item, domain, eta, a, new_b, new_s, SIGMA, MU, prev_a_num, prev_a_denom, dec_st) {
    .Call('_VEMIRT_acfa3', PACKAGE = 'VEMIRT', u, indic, id_1, item, domain, eta, a, new_b, new_s, SIGMA, MU, prev_a_num, prev_a_denom, dec_st)
}

lb3pl <- function(u, xi, s, id_1, new_a, new_c, sig, new_b, SIGMA, MU, Alpha, Beta, mu_b, sigma2_b) {
    .Call('_VEMIRT_lb3pl', PACKAGE = 'VEMIRT', u, xi, s, id_1, new_a, new_c, sig, new_b, SIGMA, MU, Alpha, Beta, mu_b, sigma2_b)
}

eefa2 <- function(u, domain, person, item, eta, new_a, new_b) {
    .Call('_VEMIRT_eefa2', PACKAGE = 'VEMIRT', u, domain, person, item, eta, new_a, new_b)
}

aefa2 <- function(u, domain, person, item, eta, new_b, SIGMA, MU) {
    .Call('_VEMIRT_aefa2', PACKAGE = 'VEMIRT', u, domain, person, item, eta, new_b, SIGMA, MU)
}

paal2pl <- function(u, domain, person, lbd, sdf, eta, a, new_b, SIGMA, MU, weights) {
    .Call('_VEMIRT_paal2pl', PACKAGE = 'VEMIRT', u, domain, person, lbd, sdf, eta, a, new_b, SIGMA, MU, weights)
}

paalc22pl <- function(u, a, indic, nopenalty_col, lastone, lbd, person, eta, new_b, SIGMA, MU, weights) {
    .Call('_VEMIRT_paalc22pl', PACKAGE = 'VEMIRT', u, a, indic, nopenalty_col, lastone, lbd, person, eta, new_b, SIGMA, MU, weights)
}

paalc22pl1 <- function(u, domain, item, person, lbd, eta, new_a, new_b, SIGMA, MU, pc, weights) {
    .Call('_VEMIRT_paalc22pl1', PACKAGE = 'VEMIRT', u, domain, item, person, lbd, eta, new_a, new_b, SIGMA, MU, pc, weights)
}

nalc12pl <- function(u, indic, nopenalty_col, person, eta, new_b, SIGMA, MU) {
    .Call('_VEMIRT_nalc12pl', PACKAGE = 'VEMIRT', u, indic, nopenalty_col, person, eta, new_b, SIGMA, MU)
}

palc12pl <- function(u, domain, person, lbd, sdf, eta, a, new_b, SIGMA, MU) {
    .Call('_VEMIRT_palc12pl', PACKAGE = 'VEMIRT', u, domain, person, lbd, sdf, eta, a, new_b, SIGMA, MU)
}

nalc22pl <- function(u, domain, a, nopenalty_col, lastone, person, eta, new_b, SIGMA, MU) {
    .Call('_VEMIRT_nalc22pl', PACKAGE = 'VEMIRT', u, domain, a, nopenalty_col, lastone, person, eta, new_b, SIGMA, MU)
}

palc22pl <- function(u, a, nopenalty_col, lastone, lbd, person, eta, new_b, SIGMA, MU) {
    .Call('_VEMIRT_palc22pl', PACKAGE = 'VEMIRT', u, a, nopenalty_col, lastone, lbd, person, eta, new_b, SIGMA, MU)
}

palc22pl1 <- function(u, domain, item, person, lbd, eta, new_a, new_b, SIGMA, MU, pc) {
    .Call('_VEMIRT_palc22pl1', PACKAGE = 'VEMIRT', u, domain, item, person, lbd, eta, new_a, new_b, SIGMA, MU, pc)
}

eefa3 <- function(u, domain, id_1, item, eta, new_s, new_a, new_b, SIGMA1, MU1, xi1) {
    .Call('_VEMIRT_eefa3', PACKAGE = 'VEMIRT', u, domain, id_1, item, eta, new_s, new_a, new_b, SIGMA1, MU1, xi1)
}

aefa3 <- function(u, id_1, item, domain, eta, a, new_b, new_s, SIGMA, MU, prev_a_num, prev_a_denom, dec_st) {
    .Call('_VEMIRT_aefa3', PACKAGE = 'VEMIRT', u, id_1, item, domain, eta, a, new_b, new_s, SIGMA, MU, prev_a_num, prev_a_denom, dec_st)
}

paal3pl <- function(u, domain, item, id_1, lbd, eta, s, a, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, weights, sdf) {
    .Call('_VEMIRT_paal3pl', PACKAGE = 'VEMIRT', u, domain, item, id_1, lbd, eta, s, a, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, weights, sdf)
}

paalc23pl <- function(u, a, nopenalty_col, s, lastone, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, weights) {
    .Call('_VEMIRT_paalc23pl', PACKAGE = 'VEMIRT', u, a, nopenalty_col, s, lastone, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, weights)
}

paalc23pl1 <- function(u, a, s, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, pc, delta1, deriv22, weights) {
    .Call('_VEMIRT_paalc23pl1', PACKAGE = 'VEMIRT', u, a, s, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, pc, delta1, deriv22, weights)
}

nalc13pl <- function(u, indic, nopenalty_col, eta, s, new_b, SIGMA, MU, a, id_1, prev_a_num, prev_a_denom, dec_st) {
    .Call('_VEMIRT_nalc13pl', PACKAGE = 'VEMIRT', u, indic, nopenalty_col, eta, s, new_b, SIGMA, MU, a, id_1, prev_a_num, prev_a_denom, dec_st)
}

palc13pl <- function(u, domain, item, id_1, lbd, eta, s, a, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, sdf) {
    .Call('_VEMIRT_palc13pl', PACKAGE = 'VEMIRT', u, domain, item, id_1, lbd, eta, s, a, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, sdf)
}

nalc23pl <- function(u, domain, item, a, nopenalty_col, lastone, s, eta, new_b, SIGMA, MU, id_1, prev_a_num, prev_a_denom, dec_st) {
    .Call('_VEMIRT_nalc23pl', PACKAGE = 'VEMIRT', u, domain, item, a, nopenalty_col, lastone, s, eta, new_b, SIGMA, MU, id_1, prev_a_num, prev_a_denom, dec_st)
}

palc23pl <- function(u, a, nopenalty_col, s, lastone, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2) {
    .Call('_VEMIRT_palc23pl', PACKAGE = 'VEMIRT', u, a, nopenalty_col, s, lastone, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2)
}

palc23pl1 <- function(u, a, s, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, pc, delta1, deriv22) {
    .Call('_VEMIRT_palc23pl1', PACKAGE = 'VEMIRT', u, a, s, lbd, id_1, eta, new_b, SIGMA, MU, dec_st, prev_delta, prev_deriv2, pc, delta1, deriv22)
}

sumoverk <- function(G, rgky, aj, dj, betjy, gamjy, X) {
    .Call('_VEMIRT_sumoverk', PACKAGE = 'VEMIRT', G, rgky, aj, dj, betjy, gamjy, X)
}

ngest <- function(LiA, y, Nvec, G) {
    .Call('_VEMIRT_ngest', PACKAGE = 'VEMIRT', LiA, y, Nvec, G)
}

rgkest <- function(j, Xijk, LiA, y, Nvec, G, N, m) {
    .Call('_VEMIRT_rgkest', PACKAGE = 'VEMIRT', j, Xijk, LiA, y, Nvec, G, N, m)
}

eigenMapMatMult <- function(A, B) {
    .Call('_VEMIRT_eigenMapMatMult', PACKAGE = 'VEMIRT', A, B)
}

dmvnrm2 <- function(x, mean, sigma, logd = FALSE) {
    .Call('_VEMIRT_dmvnrm2', PACKAGE = 'VEMIRT', x, mean, sigma, logd)
}

Estep1 <- function(resp, Nvec, X, y, G, yallgroup, Mulist, Siglist, gra, grd, grbeta, grgamma, r, J, m, N) {
    .Call('_VEMIRT_Estep1', PACKAGE = 'VEMIRT', resp, Nvec, X, y, G, yallgroup, Mulist, Siglist, gra, grd, grbeta, grgamma, r, J, m, N)
}

scocal <- function(j, ng, rgk, a, d, bet, gam, maxtol, X, yallgroup, y, G, r, m, eta) {
    .Call('_VEMIRT_scocal', PACKAGE = 'VEMIRT', j, ng, rgk, a, d, bet, gam, maxtol, X, yallgroup, y, G, r, m, eta)
}

soft2 <- function(s, tau) {
    .Call('_VEMIRT_soft2', PACKAGE = 'VEMIRT', s, tau)
}

Mstep <- function(j, ng, rgk, gra, grd, grbeta, grgamma, maxtol, X, yallgroup, y, G, r, m, eta) {
    .Call('_VEMIRT_Mstep', PACKAGE = 'VEMIRT', j, ng, rgk, gra, grd, grbeta, grgamma, maxtol, X, yallgroup, y, G, r, m, eta)
}

Mstepadapt <- function(j, ng, rgk, gra, grd, grbeta, grbeta00, grgamma, grgamma00, maxtol, X, yallgroup, y, G, r, m, eta, lam) {
    .Call('_VEMIRT_Mstepadapt', PACKAGE = 'VEMIRT', j, ng, rgk, gra, grd, grbeta, grbeta00, grgamma, grgamma00, maxtol, X, yallgroup, y, G, r, m, eta, lam)
}

sampling <- function(mu_i, sig_i, person, domain, S, M) {
    .Call('_VEMIRT_sampling', PACKAGE = 'VEMIRT', mu_i, sig_i, person, domain, S, M)
}

importance_weights <- function(theta_IS, mu_i, sig_i, a, b, Sigma_theta, y, person, item, S, M) {
    .Call('_VEMIRT_importance_weights', PACKAGE = 'VEMIRT', theta_IS, mu_i, sig_i, a, b, Sigma_theta, y, person, item, S, M)
}

importance_gradient <- function(y, a, b, Sigma_theta, theta_IS, w_tilde, S, M) {
    .Call('_VEMIRT_importance_gradient', PACKAGE = 'VEMIRT', y, a, b, Sigma_theta, theta_IS, w_tilde, S, M)
}

